// Drizzle schema for the QIS tracker.
//
// `records` holds every CAPA / NCR / Audit-finding row. Each row is tagged with
// a `site` so the header site selector can scope the view to a single facility.
// Audit-trail columns (created_by/at, modified_by/at) live on the row itself;
// the `audit_log` table below captures the full per-change history.
import { pgTable, serial, text, timestamp, boolean, jsonb, index, uniqueIndex } from "drizzle-orm/pg-core";

export const records = pgTable(
  "records",
  {
    // Human-readable identifier generated by the app (e.g. "QIS-0001",
    // "NCR-LDN-2026-001"). Used as the primary key so existing IDs are stable.
    id: text("id").primaryKey(),
    type: text("type").notNull().default("CAPA"),
    severity: text("severity").notNull().default("Minor"),
    clause: text("clause").notNull().default(""),
    status: text("status").notNull().default("Open"),
    dueDate: text("due_date").notNull().default(""),
    owner: text("owner").notNull().default(""),
    ca: text("ca").notNull().default(""),
    rca: text("rca").notNull().default(""),
    description: text("description").notNull().default(""),
    site: text("site").notNull().default("Lindon"),
    // Free-text objective-evidence notes and embedded photo/file attachments.
    // Kept so the existing UI continues to work exactly as before.
    evidence: text("evidence").notNull().default(""),
    photos: jsonb("photos").$type<any[]>().notNull().default([]),
    selfAssigned: boolean("self_assigned").notNull().default(false),
    // Links a finding back to the audit session it was raised against. Used by
    // the audits function to refuse closing a session while linked findings
    // remain open. Empty when the record is not tied to an audit session.
    auditId: text("audit_id").notNull().default(""),
    // Direct single-CAPA linkage for NCR / Audit Finding records (the source
    // record points at the CAPA that addresses it). Empty when not linked.
    capaId: text("capa_id").notNull().default(""),
    // Effectiveness-check state tracked directly on a CAPA record so the list
    // views can show it without a join. The authoritative effectiveness record
    // lives in the effectiveness_checks table below.
    effectivenessCheckDueDate: text("effectiveness_check_due_date").notNull().default(""),
    effectivenessCheckOwner: text("effectiveness_check_owner").notNull().default(""),
    effectivenessStatus: text("effectiveness_status").notNull().default(""),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    // Audit-trail columns.
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("records_site_idx").on(t.site),
  })
);

// ── CAPA LINKAGE ─────────────────────────────────────────────────────────────
// Many-to-many linkage between a CAPA record and the source items it addresses
// (NCRs, Audit Findings, OOS investigations, Crisis Exercises). One row per
// link. `linked_by` is stamped server-side from the signed-in identity. The
// records.capa_id column above covers the simple single-CAPA case; this table
// covers a CAPA that rolls up multiple sources.
export const capaLinks = pgTable(
  "capa_links",
  {
    id: text("id").primaryKey(),
    capaId: text("capa_id").notNull(),
    // NCR | Audit Finding | OOS | Crisis Exercise
    sourceType: text("source_type").notNull(),
    sourceId: text("source_id").notNull(),
    linkedBy: text("linked_by").notNull(),
    linkedAt: timestamp("linked_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    capaIdx: index("capa_links_capa_idx").on(t.capaId),
    sourceIdx: index("capa_links_source_idx").on(t.sourceId),
  })
);

// ── EFFECTIVENESS CHECKS ─────────────────────────────────────────────────────
// One row per CAPA effectiveness check. After a CAPA is closed and its check
// owner has been assigned, the check is scheduled (Pending), conducted
// (In Progress) and finally completed with a determination of Effective /
// Ineffective / Requires Additional Action. The due date is adjustable at any
// time before the check is completed.
export const effectivenessChecks = pgTable(
  "effectiveness_checks",
  {
    id: text("id").primaryKey(),
    capaId: text("capa_id").notNull(),
    // Adjustable at any time before the check is completed.
    dueDate: text("due_date"),
    // The person responsible for conducting the effectiveness check.
    owner: text("owner").notNull(),
    // Pending | In Progress | Completed
    status: text("status").notNull().default("Pending"),
    rootCauseEliminated: text("root_cause_eliminated").notNull().default(""),
    evidence: text("evidence").notNull().default(""),
    recurred: text("recurred").notNull().default(""),
    // Effective | Ineffective | Requires Additional Action
    determination: text("determination").notNull().default(""),
    verifiedBy: text("verified_by").notNull().default(""),
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    capaIdx: index("effectiveness_checks_capa_idx").on(t.capaId),
  })
);

// ── AUDIT SESSIONS (Internal Audit Program — Form SOP-22) ───────────────────
// One row per scheduled internal-audit session. A session is created in the
// "Scheduled" state, moves to "In Progress" when an auditor starts it (which
// stamps start_time and started_by), and finally to "Closed" once every linked
// NCR / CAPA finding raised against it has been closed. The per-clause working
// state lives in the `sections` jsonb array, and electronic sign-offs live in
// the `signatures` jsonb array (one entry per required role).
export const auditSessions = pgTable(
  "audit_sessions",
  {
    // Human-readable identifier (e.g. "AUDIT-LDN-2026-001-S1").
    id: text("id").primaryKey(),
    site: text("site").notNull().default("Lindon"),
    scheduledDate: text("scheduled_date").notNull().default(""),
    status: text("status").notNull().default("Scheduled"), // Scheduled | In Progress | Closed
    // Stamped server-side from the signed-in identity when the session starts.
    startTime: timestamp("start_time", { withTimezone: true }),
    startedBy: text("started_by").notNull().default(""),
    building: text("building").notNull().default(""),
    facilityAddress: text("facility_address").notNull().default(""),
    facilityName: text("facility_name").notNull().default(""),
    clausesLabel: text("clauses_label").notNull().default(""),
    // Per-clause working state: [{ id, title, status, notes, photos, ... }].
    sections: jsonb("sections").$type<any[]>().notNull().default([]),
    // Auditor's transient execution / walk-through state (current step, UI
    // cursor, scratch values) persisted so an in-progress audit can be resumed.
    execState: jsonb("exec_state").$type<Record<string, any>>().notNull().default({}),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("audit_sessions_site_idx").on(t.site),
  })
);

// ── CRISIS MANAGEMENT EXERCISE (Form SOP-20-EX-001) ─────────────────────────
// One row per crisis exercise. The header fields, scenario narrative and the
// facilitator-managed structured sections (objectives, discussion Q&A, lessons
// learned, attendees) and the overall assessment all live on this row. The live
// CMT response timeline lives in its own append-only table below so any number
// of participants can add entries concurrently without clobbering each other.
export const crisisExercises = pgTable(
  "crisis_exercises",
  {
    // Human-readable identifier generated by the app, format CMT-EX-YYYY-NNN.
    id: text("id").primaryKey(),
    exerciseType: text("exercise_type").notNull().default(""),
    scenarioName: text("scenario_name").notNull().default(""),
    scenarioType: text("scenario_type").notNull().default(""),
    exerciseDate: text("exercise_date").notNull().default(""),
    facilitator: text("facilitator").notNull().default(""),
    exerciseFormat: text("exercise_format").notNull().default(""),
    governingSop: text("governing_sop").notNull().default("SOP #20 | SQF Clause 2.6.4"),
    site: text("site").notNull().default("Lindon"),
    scenarioNarrative: text("scenario_narrative").notNull().default(""),
    // [{ num, desc }]
    objectives: jsonb("objectives").$type<any[]>().notNull().default([]),
    // [{ id, question, by, responses: [{ user, text, at }] }]
    discussion: jsonb("discussion").$type<any[]>().notNull().default([]),
    // [{ item, owner, targetDate, capaRequired, capaId }]
    lessonsLearned: jsonb("lessons_learned").$type<any[]>().notNull().default([]),
    // [{ name, title, qualifications, role, signoffAt }]
    attendees: jsonb("attendees").$type<any[]>().notNull().default([]),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    // Overall assessment.
    outcome: text("outcome").notNull().default(""),
    responseAdequate: text("response_adequate").notNull().default(""),
    planUpdateRequired: text("plan_update_required").notNull().default(""),
    nextExerciseDate: text("next_exercise_date").notNull().default(""),
    summaryNotes: text("summary_notes").notNull().default(""),
    status: text("status").notNull().default("In Progress"), // In Progress | Complete
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("crisis_exercises_site_idx").on(t.site),
  })
);

// Live, append-only CMT response timeline. One row per response entry; the
// timestamp and the user name are captured server-side from the request time
// and the signed-in identity so the chronological record is tamper-evident.
export const crisisResponseLog = pgTable(
  "crisis_response_log",
  {
    id: serial("id").primaryKey(),
    exerciseId: text("exercise_id").notNull(),
    loggedAt: timestamp("logged_at", { withTimezone: true }).notNull().defaultNow(),
    userName: text("user_name").notNull().default(""),
    phase: text("phase").notNull().default(""),
    program: text("program").notNull().default(""),
    action: text("action").notNull().default(""),
    outcome: text("outcome").notNull().default(""),
    docRef: text("doc_ref").notNull().default(""),
    status: text("status").notNull().default("Active"), // Active | Resolved
  },
  (t) => ({
    exerciseIdx: index("crisis_response_log_exercise_idx").on(t.exerciseId),
  })
);

// Append-only history of every create, update and status change. One row is
// written per mutation so the complete trail of who-changed-what-when survives.
export const auditLog = pgTable(
  "audit_log",
  {
    id: serial("id").primaryKey(),
    recordId: text("record_id").notNull(),
    action: text("action").notNull(), // create | update | status_change | delete
    detail: text("detail").notNull().default(""),
    changedBy: text("changed_by").notNull().default(""),
    changedAt: timestamp("changed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    recordIdx: index("audit_log_record_idx").on(t.recordId),
  })
);

// ── OUT OF SPECIFICATION (OOS) INVESTIGATIONS ───────────────────────────────
// One row per OOS investigation for dietary-supplement manufacturing under
// 21 CFR Part 111 and SQF Edition 9. The phased investigation (Phase 1 lab,
// Phase 2 manufacturing), root-cause analysis, disposition and closure all live
// on the row. File attachments (Original CoA, retest results, chromatograms,
// batch-record extracts, third-party lab reports, etc.) are stored in Netlify
// Blobs; only their metadata — blob key, filename, content type, size and a
// description label — is kept here in the `attachments` array. Every mutation is
// also written to the shared `audit_log` table keyed by the OOS id.
export const oosRecords = pgTable(
  "oos_records",
  {
    // Human-readable identifier generated by the app, format OOS-YYYY-NNN.
    id: text("id").primaryKey(),
    site: text("site").notNull().default("Lindon"),
    materialType: text("material_type").notNull().default(""),
    productName: text("product_name").notNull().default(""),
    supplier: text("supplier").notNull().default(""),
    internalLot: text("internal_lot").notNull().default(""),
    supplierLot: text("supplier_lot").notNull().default(""),
    batchRecordNumber: text("batch_record_number").notNull().default(""),
    manufacturingDate: text("manufacturing_date").notNull().default(""),
    expirationDate: text("expiration_date").notNull().default(""),
    testAnalyte: text("test_analyte").notNull().default(""),
    testMethod: text("test_method").notNull().default(""),
    specification: text("specification").notNull().default(""),
    resultObtained: text("result_obtained").notNull().default(""),
    units: text("units").notNull().default(""),
    passFail: text("pass_fail").notNull().default(""),
    classification: text("classification").notNull().default(""),
    phase1Notes: text("phase1_notes").notNull().default(""),
    phase2Notes: text("phase2_notes").notNull().default(""),
    rootCause: text("root_cause").notNull().default(""),
    rootCauseCategory: text("root_cause_category").notNull().default(""),
    correctiveAction: text("corrective_action").notNull().default(""),
    disposition: text("disposition").notNull().default("Pending"),
    capaId: text("capa_id").notNull().default(""),
    status: text("status").notNull().default("Open"),
    // Captured server-side from the signed-in identity at creation / closure.
    initiatedBy: text("initiated_by").notNull().default(""),
    closedBy: text("closed_by").notNull().default(""),
    closedDate: text("closed_date").notNull().default(""),
    // [{ key, filename, contentType, size, description, uploadedBy, uploadedAt }]
    attachments: jsonb("attachments").$type<any[]>().notNull().default([]),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("oos_records_site_idx").on(t.site),
  })
);

// ── MANAGEMENT REPORT DRAFTS (Monthly Flash / Annual Management Review) ──────
// The Monthly Quality Flash Report and the Annual Management Review pull all of
// their metrics live from the other tables at generation time — nothing about
// those numbers is stored here. What IS stored is the editable NARRATIVE that a
// reviewer types into the report (attendee lists, policy-update notes, supplier
// performance notes, quality-objective tables, management decisions, etc.) so a
// report can be saved and resumed across multiple sessions. One row per
// (report type, period, site); the free-form fields live in the `data` blob.
export const reportDrafts = pgTable(
  "report_drafts",
  {
    id: serial("id").primaryKey(),
    reportType: text("report_type").notNull(), // monthly-flash | annual-review
    period: text("period").notNull(),          // "YYYY-MM" (monthly) or "YYYY" (annual)
    site: text("site").notNull().default(""),  // "" = all sites
    // Arbitrary map of editable narrative field id → value.
    data: jsonb("data").$type<Record<string, any>>().notNull().default({}),
    updatedBy: text("updated_by").notNull().default(""),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    keyIdx: uniqueIndex("report_drafts_key_idx").on(t.reportType, t.period, t.site),
  })
);
