// Drizzle schema for the QIS tracker.
//
// `records` holds every CAPA / NCR / Audit-finding row. Each row is tagged with
// a `site` so the header site selector can scope the view to a single facility.
// Audit-trail columns (created_by/at, modified_by/at) live on the row itself;
// the `audit_log` table below captures the full per-change history.
import { pgTable, serial, text, timestamp, boolean, jsonb, integer, numeric, index, uniqueIndex } from "drizzle-orm/pg-core";

export const records = pgTable(
  "records",
  {
    // Human-readable identifier generated by the app (e.g. "QIS-0001",
    // "NCR-LDN-2026-001"). Used as the primary key so existing IDs are stable.
    id: text("id").primaryKey(),
    type: text("type").notNull().default("CAPA"),
    severity: text("severity").notNull().default("Minor"),
    // ── Risk matrix (Likelihood × Severity) ──────────────────────────────────
    // The existing `severity` column above remains the qualitative
    // classification (Minor / Major / Critical). The risk matrix adds a separate
    // numeric 1-5 likelihood and 1-5 severity whose product drives risk_score /
    // risk_level. Stored as text so the empty "" default = "not yet scored".
    likelihood: text("likelihood").notNull().default(""),
    riskSeverity: text("risk_severity").notNull().default(""),
    riskScore: integer("risk_score").notNull().default(0),
    riskLevel: text("risk_level").notNull().default(""),
    // ── Residual risk (post-corrective-action) ───────────────────────────────
    // For CAPA records: the re-scored Likelihood × Severity AFTER the corrective
    // action, so the two-stage risk-reduction story (initial finding risk →
    // post-CA residual risk) can be told in the UI and reports. Same 1-5 inputs,
    // same product → level thresholds as the initial risk above. risk_reduction_pct
    // is the auto-calculated % reduction from the inherited initial source-finding
    // risk score to this residual score. Empty "" / 0 = "not yet re-assessed".
    postCaLikelihood: text("post_ca_likelihood").notNull().default(""),
    postCaSeverity: text("post_ca_severity").notNull().default(""),
    postCaRiskScore: integer("post_ca_risk_score").notNull().default(0),
    postCaRiskLevel: text("post_ca_risk_level").notNull().default(""),
    riskReductionPct: integer("risk_reduction_pct").notNull().default(0),
    // Free-text residual-risk remarks (auto-suggested from the post-CA level, then
    // editable by the user) — shown in the residual-risk UI and the PDF reports.
    postCaRemarks: text("post_ca_remarks").notNull().default(""),
    clause: text("clause").notNull().default(""),
    status: text("status").notNull().default("Open"),
    dueDate: text("due_date").notNull().default(""),
    owner: text("owner").notNull().default(""),
    ca: text("ca").notNull().default(""),
    rca: text("rca").notNull().default(""),
    description: text("description").notNull().default(""),
    site: text("site").notNull().default("Lindon"),
    // Free-text objective-evidence notes and embedded photo/file attachments.
    // Kept so the existing UI continues to work exactly as before.
    evidence: text("evidence").notNull().default(""),
    photos: jsonb("photos").$type<any[]>().notNull().default([]),
    selfAssigned: boolean("self_assigned").notNull().default(false),
    // Links a finding back to the audit session it was raised against. Used by
    // the audits function to refuse closing a session while linked findings
    // remain open. Empty when the record is not tied to an audit session.
    auditId: text("audit_id").notNull().default(""),
    // Source / certification body for Audit Finding records (e.g. "NSF", "SQF"
    // or a custom 1-3 letter code). Drives the prefix of the auto-generated
    // record id (e.g. "NSF-LDN-2026-001") and is shown on the detail view and
    // in reports. Empty for record types that carry no certification-body source.
    sourceBody: text("source_body").notNull().default(""),
    // Direct single-CAPA linkage for NCR / Audit Finding records (the source
    // record points at the CAPA that addresses it). Empty when not linked.
    capaId: text("capa_id").notNull().default(""),
    // Effectiveness-check state tracked directly on a CAPA record so the list
    // views can show it without a join. The authoritative effectiveness record
    // lives in the effectiveness_checks table below.
    effectivenessCheckDueDate: text("effectiveness_check_due_date").notNull().default(""),
    effectivenessCheckOwner: text("effectiveness_check_owner").notNull().default(""),
    effectivenessStatus: text("effectiveness_status").notNull().default(""),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    // Audit-trail columns.
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("records_site_idx").on(t.site),
    // Indexes on the columns the list views filter and sort by. The single-column
    // indexes cover queries that scope by one field; the composite indexes cover
    // the common site + type / site + status / site + type + status combinations
    // the front-end uses so those queries never fall back to a full table scan.
    typeIdx: index("records_type_idx").on(t.type),
    statusIdx: index("records_status_idx").on(t.status),
    siteTypeIdx: index("records_site_type_idx").on(t.site, t.type),
    siteStatusIdx: index("records_site_status_idx").on(t.site, t.status),
    siteTypeStatusIdx: index("records_site_type_status_idx").on(t.site, t.type, t.status),
    createdAtIdx: index("records_created_at_idx").on(t.createdAt),
    dueDateIdx: index("records_due_date_idx").on(t.dueDate),
    capaIdIdx: index("records_capa_id_idx").on(t.capaId),
  })
);

// ── CAPA LINKAGE ─────────────────────────────────────────────────────────────
// Many-to-many linkage between a CAPA record and the source items it addresses
// (NCRs, Audit Findings, OOS investigations, Crisis Exercises). One row per
// link. `linked_by` is stamped server-side from the signed-in identity. The
// records.capa_id column above covers the simple single-CAPA case; this table
// covers a CAPA that rolls up multiple sources.
export const capaLinks = pgTable(
  "capa_links",
  {
    id: text("id").primaryKey(),
    capaId: text("capa_id").notNull(),
    // NCR | Audit Finding | OOS | Crisis Exercise
    sourceType: text("source_type").notNull(),
    sourceId: text("source_id").notNull(),
    linkedBy: text("linked_by").notNull(),
    linkedAt: timestamp("linked_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    capaIdx: index("capa_links_capa_idx").on(t.capaId),
    sourceIdx: index("capa_links_source_idx").on(t.sourceId),
    // Covers the "links for one CAPA of a given source type" lookups.
    capaSourceTypeIdx: index("capa_links_capa_source_type_idx").on(t.capaId, t.sourceType),
  })
);

// ── EFFECTIVENESS CHECKS ─────────────────────────────────────────────────────
// One row per CAPA effectiveness check. After a CAPA is closed and its check
// owner has been assigned, the check is scheduled (Pending), conducted
// (In Progress) and finally completed with a determination of Effective /
// Ineffective / Requires Additional Action. The due date is adjustable at any
// time before the check is completed.
export const effectivenessChecks = pgTable(
  "effectiveness_checks",
  {
    id: text("id").primaryKey(),
    capaId: text("capa_id").notNull(),
    // Adjustable at any time before the check is completed.
    dueDate: text("due_date"),
    // The person responsible for conducting the effectiveness check.
    owner: text("owner").notNull(),
    // Pending | In Progress | Completed
    status: text("status").notNull().default("Pending"),
    rootCauseEliminated: text("root_cause_eliminated").notNull().default(""),
    evidence: text("evidence").notNull().default(""),
    recurred: text("recurred").notNull().default(""),
    // Effective | Ineffective | Requires Additional Action
    determination: text("determination").notNull().default(""),
    verifiedBy: text("verified_by").notNull().default(""),
    verifiedAt: timestamp("verified_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    capaIdx: index("effectiveness_checks_capa_idx").on(t.capaId),
    statusIdx: index("effectiveness_checks_status_idx").on(t.status),
  })
);

// ── AUDIT SESSIONS (Internal Audit Program — Form SOP-22) ───────────────────
// One row per scheduled internal-audit session. A session is created in the
// "Scheduled" state, moves to "In Progress" when an auditor starts it (which
// stamps start_time and started_by), and finally to "Closed" once every linked
// NCR / CAPA finding raised against it has been closed. The per-clause working
// state lives in the `sections` jsonb array, and electronic sign-offs live in
// the `signatures` jsonb array (one entry per required role).
export const auditSessions = pgTable(
  "audit_sessions",
  {
    // Human-readable identifier (e.g. "AUDIT-LDN-2026-001-S1").
    id: text("id").primaryKey(),
    site: text("site").notNull().default("Lindon"),
    scheduledDate: text("scheduled_date").notNull().default(""),
    status: text("status").notNull().default("Scheduled"), // Scheduled | In Progress | Closed
    // Stamped server-side from the signed-in identity when the session starts.
    startTime: timestamp("start_time", { withTimezone: true }),
    startedBy: text("started_by").notNull().default(""),
    building: text("building").notNull().default(""),
    facilityAddress: text("facility_address").notNull().default(""),
    facilityName: text("facility_name").notNull().default(""),
    clausesLabel: text("clauses_label").notNull().default(""),
    // Per-clause working state: [{ id, title, status, notes, photos, ... }].
    sections: jsonb("sections").$type<any[]>().notNull().default([]),
    // Auditor's transient execution / walk-through state (current step, UI
    // cursor, scratch values) persisted so an in-progress audit can be resumed.
    execState: jsonb("exec_state").$type<Record<string, any>>().notNull().default({}),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("audit_sessions_site_idx").on(t.site),
    statusIdx: index("audit_sessions_status_idx").on(t.status),
    scheduledDateIdx: index("audit_sessions_scheduled_date_idx").on(t.scheduledDate),
  })
);

// ── CRISIS MANAGEMENT EXERCISE (Form SOP-20-EX-001) ─────────────────────────
// One row per crisis exercise. The header fields, scenario narrative and the
// facilitator-managed structured sections (objectives, discussion Q&A, lessons
// learned, attendees) and the overall assessment all live on this row. The live
// CMT response timeline lives in its own append-only table below so any number
// of participants can add entries concurrently without clobbering each other.
export const crisisExercises = pgTable(
  "crisis_exercises",
  {
    // Human-readable identifier generated by the app, format CMT-EX-YYYY-NNN.
    id: text("id").primaryKey(),
    exerciseType: text("exercise_type").notNull().default(""),
    scenarioName: text("scenario_name").notNull().default(""),
    scenarioType: text("scenario_type").notNull().default(""),
    exerciseDate: text("exercise_date").notNull().default(""),
    facilitator: text("facilitator").notNull().default(""),
    exerciseFormat: text("exercise_format").notNull().default(""),
    governingSop: text("governing_sop").notNull().default("SOP #20 | SQF Clause 2.6.4"),
    site: text("site").notNull().default("Lindon"),
    scenarioNarrative: text("scenario_narrative").notNull().default(""),
    // [{ num, desc }]
    objectives: jsonb("objectives").$type<any[]>().notNull().default([]),
    // [{ id, question, by, responses: [{ user, text, at }] }]
    discussion: jsonb("discussion").$type<any[]>().notNull().default([]),
    // [{ item, owner, targetDate, capaRequired, capaId }]
    lessonsLearned: jsonb("lessons_learned").$type<any[]>().notNull().default([]),
    // Aggregated risk data rolled up from the lessons-learned rows' risk scores
    // (e.g. { counts: { Critical, High, Medium, Low }, highest, items: [...] }).
    // Recomputed server-side whenever lessons learned change.
    findingsRiskSummary: jsonb("findings_risk_summary").$type<Record<string, any>>().notNull().default({}),
    // [{ name, title, qualifications, role, signoffAt }]
    attendees: jsonb("attendees").$type<any[]>().notNull().default([]),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    // Overall assessment.
    outcome: text("outcome").notNull().default(""),
    responseAdequate: text("response_adequate").notNull().default(""),
    planUpdateRequired: text("plan_update_required").notNull().default(""),
    nextExerciseDate: text("next_exercise_date").notNull().default(""),
    summaryNotes: text("summary_notes").notNull().default(""),
    status: text("status").notNull().default("In Progress"), // In Progress | Complete
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("crisis_exercises_site_idx").on(t.site),
    statusIdx: index("crisis_exercises_status_idx").on(t.status),
  })
);

// Live, append-only CMT response timeline. One row per response entry; the
// timestamp and the user name are captured server-side from the request time
// and the signed-in identity so the chronological record is tamper-evident.
export const crisisResponseLog = pgTable(
  "crisis_response_log",
  {
    id: serial("id").primaryKey(),
    exerciseId: text("exercise_id").notNull(),
    loggedAt: timestamp("logged_at", { withTimezone: true }).notNull().defaultNow(),
    userName: text("user_name").notNull().default(""),
    phase: text("phase").notNull().default(""),
    program: text("program").notNull().default(""),
    action: text("action").notNull().default(""),
    outcome: text("outcome").notNull().default(""),
    docRef: text("doc_ref").notNull().default(""),
    status: text("status").notNull().default("Active"), // Active | Resolved
  },
  (t) => ({
    exerciseIdx: index("crisis_response_log_exercise_idx").on(t.exerciseId),
  })
);

// Append-only history of every create, update and status change. One row is
// written per mutation so the complete trail of who-changed-what-when survives.
export const auditLog = pgTable(
  "audit_log",
  {
    id: serial("id").primaryKey(),
    recordId: text("record_id").notNull(),
    action: text("action").notNull(), // create | update | status_change | delete
    detail: text("detail").notNull().default(""),
    changedBy: text("changed_by").notNull().default(""),
    changedAt: timestamp("changed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    recordIdx: index("audit_log_record_idx").on(t.recordId),
    // The append-only trail's timestamp column is `changed_at` (there is no
    // `created_at` on this table); index it so per-record history can be served
    // newest-first without scanning the whole log.
    changedAtIdx: index("audit_log_changed_at_idx").on(t.changedAt),
  })
);

// ── OUT OF SPECIFICATION (OOS) INVESTIGATIONS ───────────────────────────────
// One row per OOS investigation for dietary-supplement manufacturing under
// 21 CFR Part 111 and SQF Edition 9. The phased investigation (Phase 1 lab,
// Phase 2 manufacturing), root-cause analysis, disposition and closure all live
// on the row. File attachments (Original CoA, retest results, chromatograms,
// batch-record extracts, third-party lab reports, etc.) are stored in Netlify
// Blobs; only their metadata — blob key, filename, content type, size and a
// description label — is kept here in the `attachments` array. Every mutation is
// also written to the shared `audit_log` table keyed by the OOS id.
export const oosRecords = pgTable(
  "oos_records",
  {
    // Human-readable identifier generated by the app, format OOS-YYYY-NNN.
    id: text("id").primaryKey(),
    site: text("site").notNull().default("Lindon"),
    materialType: text("material_type").notNull().default(""),
    productName: text("product_name").notNull().default(""),
    supplier: text("supplier").notNull().default(""),
    internalLot: text("internal_lot").notNull().default(""),
    supplierLot: text("supplier_lot").notNull().default(""),
    batchRecordNumber: text("batch_record_number").notNull().default(""),
    manufacturingDate: text("manufacturing_date").notNull().default(""),
    expirationDate: text("expiration_date").notNull().default(""),
    testAnalyte: text("test_analyte").notNull().default(""),
    testMethod: text("test_method").notNull().default(""),
    specification: text("specification").notNull().default(""),
    resultObtained: text("result_obtained").notNull().default(""),
    units: text("units").notNull().default(""),
    passFail: text("pass_fail").notNull().default(""),
    classification: text("classification").notNull().default(""),
    // ── Risk matrix (Likelihood × Severity) ──────────────────────────────────
    // 1-5 likelihood and 1-5 severity whose product drives risk_score /
    // risk_level. Empty "" default = "not yet scored".
    likelihood: text("likelihood").notNull().default(""),
    riskSeverity: text("risk_severity").notNull().default(""),
    riskScore: integer("risk_score").notNull().default(0),
    riskLevel: text("risk_level").notNull().default(""),
    phase1Notes: text("phase1_notes").notNull().default(""),
    phase2Notes: text("phase2_notes").notNull().default(""),
    rootCause: text("root_cause").notNull().default(""),
    rootCauseCategory: text("root_cause_category").notNull().default(""),
    correctiveAction: text("corrective_action").notNull().default(""),
    disposition: text("disposition").notNull().default("Pending"),
    capaId: text("capa_id").notNull().default(""),
    status: text("status").notNull().default("Open"),
    // Captured server-side from the signed-in identity at creation / closure.
    initiatedBy: text("initiated_by").notNull().default(""),
    closedBy: text("closed_by").notNull().default(""),
    closedDate: text("closed_date").notNull().default(""),
    // [{ key, filename, contentType, size, description, uploadedBy, uploadedAt }]
    attachments: jsonb("attachments").$type<any[]>().notNull().default([]),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("oos_records_site_idx").on(t.site),
    statusIdx: index("oos_records_status_idx").on(t.status),
    siteStatusIdx: index("oos_records_site_status_idx").on(t.site, t.status),
    createdAtIdx: index("oos_records_created_at_idx").on(t.createdAt),
  })
);

// ── MANAGEMENT REPORT DRAFTS (Monthly Flash / Annual Management Review) ──────
// The Monthly Quality Flash Report and the Annual Management Review pull all of
// their metrics live from the other tables at generation time — nothing about
// those numbers is stored here. What IS stored is the editable NARRATIVE that a
// reviewer types into the report (attendee lists, policy-update notes, supplier
// performance notes, quality-objective tables, management decisions, etc.) so a
// report can be saved and resumed across multiple sessions. One row per
// (report type, period, site); the free-form fields live in the `data` blob.
export const reportDrafts = pgTable(
  "report_drafts",
  {
    id: serial("id").primaryKey(),
    reportType: text("report_type").notNull(), // monthly-flash | annual-review
    period: text("period").notNull(),          // "YYYY-MM" (monthly) or "YYYY" (annual)
    site: text("site").notNull().default(""),  // "" = all sites
    // Arbitrary map of editable narrative field id → value.
    data: jsonb("data").$type<Record<string, any>>().notNull().default({}),
    updatedBy: text("updated_by").notNull().default(""),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    keyIdx: uniqueIndex("report_drafts_key_idx").on(t.reportType, t.period, t.site),
  })
);

// ── MOCK RECALL EXERCISE (Trace & Recall — SOP #21) ─────────────────────────
// One row per recall / traceability exercise. The setup header, the rolled-up
// Stage 3 assessment metrics, the facilitator notes and the electronic
// sign-offs all live on this row. The traceability chain (one row per node) and
// the identified gaps / findings live in their own tables below so each can be
// added, edited and reordered independently. Every mutation is also written to
// the shared `audit_log` table keyed by the recall id.
export const recallExercises = pgTable(
  "recall_exercises",
  {
    // Human-readable identifier generated by the app, format RCL-[SITE]-YYYY-####.
    id: text("id").primaryKey(),
    site: text("site").notNull().default("Lindon"),
    // Mock Recall | Real Recall | Traceability Verification
    exerciseType: text("exercise_type").notNull().default("Mock Recall"),
    // Captured server-side from the signed-in identity at creation.
    initiatedBy: text("initiated_by").notNull().default(""),
    dateInitiated: timestamp("date_initiated", { withTimezone: true }).notNull().defaultNow(),
    // Finished Good | Raw Material | Packaging-Label | Packaging-Bottle |
    // Packaging-Lid | Packaging-Other | In-Process Material
    startingMaterialType: text("starting_material_type").notNull().default(""),
    startingLotNumber: text("starting_lot_number").notNull().default(""),
    // Forward | Backward | Both
    recallDirection: text("recall_direction").notNull().default("Both"),
    scenarioDescription: text("scenario_description").notNull().default(""),
    // Pre-exercise scenario script / inject read to participants at the start of
    // the exercise (simulated event, affected materials, initial conditions).
    scenarioScript: text("scenario_script").notNull().default(""),
    governingSop: text("governing_sop").notNull().default("SOP #21 — Trace and Recall"),
    // Stage 3 assessment metrics (stored as text so units / "%" travel with them).
    totalQuantityAffected: text("total_quantity_affected").notNull().default(""),
    quantityAccountedFor: text("quantity_accounted_for").notNull().default(""),
    quantityUnaccounted: text("quantity_unaccounted").notNull().default(""),
    traceabilityRate: text("traceability_rate").notNull().default(""),
    recallScope: text("recall_scope").notNull().default(""),
    regulatoryNotificationRequired: text("regulatory_notification_required").notNull().default(""),
    customerNotificationRequired: text("customer_notification_required").notNull().default(""),
    customerNotificationCount: text("customer_notification_count").notNull().default(""),
    timeToComplete: text("time_to_complete").notNull().default(""),
    // Satisfactory | Needs Improvement | Unsatisfactory
    overallAssessment: text("overall_assessment").notNull().default(""),
    facilitatorNotes: text("facilitator_notes").notNull().default(""),
    // Draft | In Progress | Completed
    status: text("status").notNull().default("Draft"),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("recall_exercises_site_idx").on(t.site),
    statusIdx: index("recall_exercises_status_idx").on(t.status),
  })
);

// One row per node in a recall's traceability chain. `node_order` drives the
// vertical-timeline ordering and is renumbered as nodes are reordered. File
// attachments (batch records, shipping documents, CoAs, etc.) are stored in
// Netlify Blobs; only their metadata is kept here in the `attachments` array.
export const recallNodes = pgTable(
  "recall_nodes",
  {
    id: text("id").primaryKey(),
    recallId: text("recall_id").notNull().default(""),
    nodeOrder: integer("node_order").notNull().default(0),
    // Raw Material Receipt | Weigh/Dispense | Blending/Manufacturing |
    // In-Process Testing | Packaging | Finished Good Release |
    // Distribution/Shipment | Customer/Retailer | On Hand Inventory |
    // Returned/Rejected
    nodeType: text("node_type").notNull().default(""),
    nodeDate: text("node_date").notNull().default(""),
    lotBatchNumber: text("lot_batch_number").notNull().default(""),
    quantity: text("quantity").notNull().default(""),
    quantityUnit: text("quantity_unit").notNull().default(""),
    location: text("location").notNull().default(""),
    responsiblePerson: text("responsible_person").notNull().default(""),
    documentsReferenced: text("documents_referenced").notNull().default(""),
    notes: text("notes").notNull().default(""),
    // Optional first-person narrative account of what was done at this stage,
    // in the responsible person's own words — woven into the AI narrative report.
    statement: text("statement").notNull().default(""),
    // Traceable | Gap Identified | Cannot Trace
    traceabilityStatus: text("traceability_status").notNull().default(""),
    // [{ key, filename, contentType, size, description, uploadedBy, uploadedAt }]
    attachments: jsonb("attachments").$type<any[]>().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    recallIdx: index("recall_nodes_recall_idx").on(t.recallId),
  })
);

// One row per identified gap / finding raised during a recall exercise. A
// finding may require a CAPA (linked by id) and/or have an NCR raised against
// it, mirroring the Crisis Exercise lessons-learned pattern.
export const recallFindings = pgTable(
  "recall_findings",
  {
    id: text("id").primaryKey(),
    recallId: text("recall_id").notNull().default(""),
    findingDescription: text("finding_description").notNull().default(""),
    // ── Risk matrix (Likelihood × Severity) ──────────────────────────────────
    // 1-5 likelihood and 1-5 severity whose product drives risk_score /
    // risk_level. Empty "" default = "not yet scored".
    likelihood: text("likelihood").notNull().default(""),
    riskSeverity: text("risk_severity").notNull().default(""),
    riskScore: integer("risk_score").notNull().default(0),
    riskLevel: text("risk_level").notNull().default(""),
    owner: text("owner").notNull().default(""),
    targetDate: text("target_date").notNull().default(""),
    capaRequired: text("capa_required").notNull().default(""),
    capaId: text("capa_id").notNull().default(""),
    ncrId: text("ncr_id").notNull().default(""),
    status: text("status").notNull().default("Open"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    recallIdx: index("recall_findings_recall_idx").on(t.recallId),
  })
);

// ── FOOD SAFETY CULTURE SURVEY ───────────────────────────────────────────────
// One row per completed Food Safety Culture survey for a site. The survey is
// scored on a 1-5.00 scale (`overall_score`); `percentage_score` is the 0-100
// value used as the primary display number across the dashboard so culture
// metrics line up visually with the other 0-100% QIS KPIs. Each survey rolls up
// nine category rows held in `culture_survey_categories` below.
export const cultureSurveys = pgTable(
  "culture_surveys",
  {
    // Human-readable id generated by the app, e.g. "CSR-LDN-2026-0001".
    id: text("id").primaryKey(),
    site: text("site").notNull().default("Lindon"),
    // Free-text label for the window the survey covers, e.g. "April 19 – May 6 2026".
    surveyPeriod: text("survey_period").notNull().default(""),
    // The date the survey closed / was recorded (YYYY-MM-DD), used for ordering.
    surveyDate: text("survey_date").notNull().default(""),
    // Raw 1-5.00 overall score and its 0-100 percentage equivalent (taken from the
    // survey data directly — never derived by multiplying the 5.0 score by 20).
    overallScore: numeric("overall_score").notNull().default("0"),
    percentageScore: numeric("percentage_score").notNull().default("0"),
    totalResponses: integer("total_responses").notNull().default(0),
    targetScore: numeric("target_score").notNull().default("80"),
    // SQF culture-maturity rating label, e.g. "Good — Acceptable Culture …".
    sqfRating: text("sqf_rating").notNull().default(""),
    // SharePoint source file the survey was synced from, when applicable.
    sharepointFileUrl: text("sharepoint_file_url").notNull().default(""),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("culture_surveys_site_idx").on(t.site),
  })
);

// One row per scored category within a survey (nine categories per survey). The
// `status` and `priority` columns drive the colour-coding and the dashboard's
// auto-generated culture improvement opportunities.
export const cultureSurveyCategories = pgTable(
  "culture_survey_categories",
  {
    id: text("id").primaryKey(),
    surveyId: text("survey_id").notNull().default(""),
    categoryName: text("category_name").notNull().default(""),
    // 1-5.00 category score and its 0-100 percentage equivalent.
    score: numeric("score").notNull().default("0"),
    percentageScore: numeric("percentage_score").notNull().default("0"),
    // Good | Needs Attention | Critical
    status: text("status").notNull().default("Good"),
    // Percentage of respondents giving a low rating for this category.
    lowRatingPct: numeric("low_rating_pct").notNull().default("0"),
    // HIGH | MEDIUM | LOW | OK
    priority: text("priority").notNull().default("OK"),
  },
  (t) => ({
    surveyIdx: index("culture_survey_categories_survey_idx").on(t.surveyId),
  })
);

// ── RECEIVING INSPECTION (Incoming Material Receipt — SOP) ───────────────────
// One row per incoming-material receiving inspection performed at the dock. The
// header, the temperature log for cold (refrigerated / frozen) shipments, the
// visual-inspection checklist results, the overall assessment, photo
// attachments and the electronic sign-offs all live on this row. Each received
// material is a separate line item in `receiving_line_items` below so any number
// of materials can be added, edited and removed independently. A rejected or
// conditionally-accepted inspection can spawn an NCR (ncr_id); a temperature
// deviation can spawn an OOS record (oos_id). Every mutation is also written to
// the shared `audit_log` table keyed by the inspection id.
export const receivingInspections = pgTable(
  "receiving_inspections",
  {
    // Human-readable identifier generated by the app, format RCV-[SITE]-YYYY-####.
    id: text("id").primaryKey(),
    site: text("site").notNull().default("Lindon"),
    inspectionDate: timestamp("inspection_date", { withTimezone: true }).notNull().defaultNow(),
    // Captured server-side from the signed-in identity at creation.
    inspectedBy: text("inspected_by").notNull().default(""),
    carrier: text("carrier").notNull().default(""),
    trailerNumber: text("trailer_number").notNull().default(""),
    poNumber: text("po_number").notNull().default(""),
    // ── Record type / chain of custody ───────────────────────────────────────
    // A single table now backs three record types. "Receiving" (the default) is
    // an inbound dock inspection; "Shipping" is an outbound shipment inspection
    // that issues a Transfer ID; "Internal Transfer" is the inbound half of an
    // inter-site transfer, linked back to the outbound Shipping record by its
    // Transfer ID. For a Shipping record `linked_transfer_id` holds its own
    // auto-issued Transfer ID (TRF-SITE-YYYY-####); for an Internal Transfer it
    // holds the Transfer ID of the Shipping record it was received against.
    recordType: text("record_type").notNull().default("Receiving"),
    linkedTransferId: text("linked_transfer_id").notNull().default(""),
    sealNumber: text("seal_number").notNull().default(""),
    destination: text("destination").notNull().default(""),
    // Expected arrival date/time for an outbound Shipping record (ISO string).
    expectedArrival: text("expected_arrival").notNull().default(""),
    // Departure temperature (outbound) and arrival temperature (inbound) for a
    // cold chain transfer, kept separate from the receiving truck/trailer/product
    // log so the chain-of-custody report can compare the two ends.
    departureTemp: text("departure_temp").notNull().default(""),
    arrivalTemp: text("arrival_temp").notNull().default(""),
    // Free-text record of any variance between what was shipped and what arrived.
    discrepancies: text("discrepancies").notNull().default(""),
    // Stamped onto the Shipping record when its Internal Transfer is received.
    receivedAt: timestamp("received_at", { withTimezone: true }),
    receivedBy: text("received_by").notNull().default(""),
    // Site at which an outbound Shipping record was received (the receiving
    // Internal Transfer record's site). Stamped alongside received_at/received_by
    // so the original shipping record can show who received it, when, and where.
    arrivalSite: text("arrival_site").notNull().default(""),
    // ── Cold shipment / temperature log ──────────────────────────────────────
    // cold_shipment is "Yes" / "No"; when "Yes" the temperature fields below are
    // captured and temp_acceptable is the auto-calculated in-range verdict.
    coldShipment: text("cold_shipment").notNull().default("No"),
    requiredTempRange: text("required_temp_range").notNull().default(""),
    truckTemp: text("truck_temp").notNull().default(""),
    trailerTemp: text("trailer_temp").notNull().default(""),
    productTemp: text("product_temp").notNull().default(""),
    tempAcceptable: text("temp_acceptable").notNull().default(""),
    // ── Visual-inspection checklist (each "Yes" / "No" / "NA") ────────────────
    trailerExteriorOk: text("trailer_exterior_ok").notNull().default(""),
    trailerInteriorOk: text("trailer_interior_ok").notNull().default(""),
    noPestActivity: text("no_pest_activity").notNull().default(""),
    sealsIntact: text("seals_intact").notNull().default(""),
    materialsSecured: text("materials_secured").notNull().default(""),
    packagingUndamaged: text("packaging_undamaged").notNull().default(""),
    labelsCorrect: text("labels_correct").notNull().default(""),
    // Accepted | Rejected | Conditional Accept
    overallResult: text("overall_result").notNull().default(""),
    notes: text("notes").notNull().default(""),
    // Linkage to a spawned NCR (rejected / conditional) and/or OOS (temp deviation).
    ncrId: text("ncr_id").notNull().default(""),
    oosId: text("oos_id").notNull().default(""),
    // [{ key, filename, contentType, size, description, uploadedBy, uploadedAt }]
    attachments: jsonb("attachments").$type<any[]>().notNull().default([]),
    // Electronic sign-offs. Each entry: { role, name, title, signedAt }.
    signatures: jsonb("signatures").$type<any[]>().notNull().default([]),
    // Open | Accepted | Rejected (set on Complete Inspection).
    status: text("status").notNull().default("Open"),
    createdBy: text("created_by").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    modifiedBy: text("modified_by").notNull().default(""),
    modifiedAt: timestamp("modified_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    siteIdx: index("receiving_inspections_site_idx").on(t.site),
    inspectionDateIdx: index("receiving_inspections_inspection_date_idx").on(t.inspectionDate),
  })
);

// One row per received material on a receiving inspection. CoA = Certificate of
// Analysis; coa_received is "Yes" / "No" and coa_reference carries the document
// number when supplied.
export const receivingLineItems = pgTable(
  "receiving_line_items",
  {
    id: text("id").primaryKey(),
    inspectionId: text("inspection_id").notNull().default(""),
    materialName: text("material_name").notNull().default(""),
    supplier: text("supplier").notNull().default(""),
    lotNumber: text("lot_number").notNull().default(""),
    quantity: text("quantity").notNull().default(""),
    quantityUnit: text("quantity_unit").notNull().default(""),
    coaReceived: text("coa_received").notNull().default(""),
    coaReference: text("coa_reference").notNull().default(""),
    // ── Internal Transfer fields ─────────────────────────────────────────────
    // For an Internal Transfer line item the external Supplier / CoA fields are
    // replaced by a reference to the internal production batch/lot and the origin
    // (shipping) site the material was transferred from.
    internalBatchLot: text("internal_batch_lot").notNull().default(""),
    originSite: text("origin_site").notNull().default(""),
    // Per-line-item CoA / receiving-doc attachments stored in Netlify Blobs.
    // Each entry: { key, filename, contentType, size, uploadedBy, uploadedAt }.
    attachments: jsonb("attachments").$type<any[]>().notNull().default([]),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    inspectionIdx: index("receiving_line_items_inspection_idx").on(t.inspectionId),
  })
);

// ── ROLE-BASED ACCESS CONTROL ────────────────────────────────────────────────
// One row per user that has been granted an explicit role. A user with no row
// here defaults to "Member" (see lib/auth.ts). Role values, lowest → highest
// privilege: Dock, Member, Quality Manager, Admin. `site` is "ALL" (every site)
// or a specific site code, reserved for future per-site scoping. `assigned_by`
// records the admin email that set the role for the access-control audit trail.
export const userRoles = pgTable(
  "user_roles",
  {
    email: text("email").primaryKey(),
    // Admin | Quality Manager | Member | Dock
    role: text("role").notNull().default("Member"),
    // "ALL" or a specific site code.
    site: text("site").notNull().default("ALL"),
    assignedBy: text("assigned_by").notNull().default(""),
    assignedAt: timestamp("assigned_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    roleIdx: index("user_roles_role_idx").on(t.role),
  })
);

// ── ACTION LOG (access-control & integrity events) ───────────────────────────
// Append-only log of every protected action, permission denial and concurrency
// conflict. Distinct from the per-record `audit_log` above: this captures the
// security / access-control events required for 21 CFR Part 11 review. `detail`
// holds any action-specific context as a free-form JSON object.
// NOTE: defined here but its CREATE TABLE lives in its own migration
// (add_action_log) so the two RBAC tables ship as separate migrations.
export const actionLog = pgTable(
  "action_log",
  {
    // Timestamp-based unique id generated by the writer (lib/auth.ts).
    id: text("id").primaryKey(),
    timestamp: timestamp("timestamp", { withTimezone: true }).notNull().defaultNow(),
    userEmail: text("user_email").notNull().default(""),
    userRole: text("user_role").notNull().default(""),
    // role_assigned | role_removed | record_created | record_closed |
    // record_deleted | effectiveness_completed | sign_added | link_added |
    // link_removed | concurrency_conflict_rejected | permission_denied
    action: text("action").notNull().default(""),
    recordType: text("record_type").notNull().default(""),
    recordId: text("record_id").notNull().default(""),
    site: text("site").notNull().default(""),
    detail: jsonb("detail").$type<Record<string, any>>().notNull().default({}),
  },
  (t) => ({
    timestampIdx: index("action_log_timestamp_idx").on(t.timestamp),
    userEmailIdx: index("action_log_user_email_idx").on(t.userEmail),
    actionIdx: index("action_log_action_idx").on(t.action),
  })
);
