CREATE TABLE "oos_records" (
	"id" text PRIMARY KEY,
	"site" text DEFAULT 'Lindon' NOT NULL,
	"material_type" text DEFAULT '' NOT NULL,
	"product_name" text DEFAULT '' NOT NULL,
	"supplier" text DEFAULT '' NOT NULL,
	"internal_lot" text DEFAULT '' NOT NULL,
	"supplier_lot" text DEFAULT '' NOT NULL,
	"batch_record_number" text DEFAULT '' NOT NULL,
	"manufacturing_date" text DEFAULT '' NOT NULL,
	"expiration_date" text DEFAULT '' NOT NULL,
	"test_analyte" text DEFAULT '' NOT NULL,
	"test_method" text DEFAULT '' NOT NULL,
	"specification" text DEFAULT '' NOT NULL,
	"result_obtained" text DEFAULT '' NOT NULL,
	"units" text DEFAULT '' NOT NULL,
	"pass_fail" text DEFAULT '' NOT NULL,
	"classification" text DEFAULT '' NOT NULL,
	"phase1_notes" text DEFAULT '' NOT NULL,
	"phase2_notes" text DEFAULT '' NOT NULL,
	"root_cause" text DEFAULT '' NOT NULL,
	"root_cause_category" text DEFAULT '' NOT NULL,
	"corrective_action" text DEFAULT '' NOT NULL,
	"disposition" text DEFAULT 'Pending' NOT NULL,
	"capa_id" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'Open' NOT NULL,
	"initiated_by" text DEFAULT '' NOT NULL,
	"closed_by" text DEFAULT '' NOT NULL,
	"closed_date" text DEFAULT '' NOT NULL,
	"attachments" jsonb DEFAULT '[]' NOT NULL,
	"created_by" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"modified_by" text DEFAULT '' NOT NULL,
	"modified_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "oos_records_site_idx" ON "oos_records" ("site");